USE data_mart;
-- ============================================================================
-- Weekly Sales Day Validation
-- Purpose:
-- Verifies that every weekly sales record starts on the same day of the week.
-- Confirms the integrity of the weekly reporting calendar.
-- ============================================================================
SELECT DISTINCT
    DAYNAME(week_date) AS day_of_week
FROM clean_weekly_sales;

-- ============================================================================
-- Missing Week Number Analysis
-- Purpose:
-- Identifies any missing ISO week numbers in the dataset.
-- Uses a recursive CTE to compare the complete week sequence (1–52)
-- against the available sales records.
-- ============================================================================
WITH RECURSIVE week_sequence (week_num) AS (
    SELECT 1
    UNION ALL
    SELECT week_num + 1
    FROM week_sequence
    WHERE week_num < 52
)
SELECT
    ws.week_num AS missing_week_number
FROM week_sequence AS ws
WHERE ws.week_num NOT IN (
    SELECT DISTINCT week_number
    FROM clean_weekly_sales
)
ORDER BY ws.week_num;

-- ============================================================================
-- Annual Transaction Summary
-- Purpose:
-- Calculates the total number of transactions completed each year.
-- Useful for identifying yearly business activity trends.
-- ============================================================================
SELECT
    calendar_year,
    SUM(transactions) AS total_transactions
FROM clean_weekly_sales
GROUP BY calendar_year
ORDER BY calendar_year;


-- ============================================================================
-- Monthly Sales by Region
-- Purpose:
-- Summarizes monthly sales performance across all operating regions.
-- Helps identify regional seasonality and revenue trends.
-- ============================================================================
SELECT
    region,
    month_number,
    SUM(sales) AS total_sales
FROM clean_weekly_sales
GROUP BY region, month_number
ORDER BY region, month_number;


-- ============================================================================
-- Platform Transaction Analysis
-- Purpose:
-- Compares the number of transactions generated by each sales platform.
-- Useful for evaluating customer purchasing channels.
-- ============================================================================
SELECT
    platform,
    SUM(transactions) AS total_transactions
FROM clean_weekly_sales
GROUP BY platform
ORDER BY total_transactions DESC;


-- ============================================================================
-- Retail vs Shopify Sales Contribution
-- Purpose:
-- Calculates the monthly percentage contribution of Retail and Shopify
-- platforms to total sales.
-- ============================================================================
SELECT
    calendar_year,
    month_number,
    ROUND(
        100.0 * SUM(CASE WHEN platform = 'Retail'  THEN sales END) / SUM(sales),
        2
    ) AS retail_pct,
    ROUND(
        100.0 * SUM(CASE WHEN platform = 'Shopify' THEN sales END) / SUM(sales),
        2
    ) AS shopify_pct
FROM clean_weekly_sales
GROUP BY calendar_year, month_number
ORDER BY calendar_year, month_number;


-- ============================================================================
-- Annual Sales Distribution by Demographic
-- Purpose:
-- Measures each demographic group's contribution to yearly sales.
-- Useful for understanding customer composition over time.
-- ============================================================================
SELECT
    calendar_year,
    demographic,
    ROUND(
        100.0 * SUM(sales) / SUM(SUM(sales)) OVER (PARTITION BY calendar_year),
        2
    ) AS pct_of_annual_sales
FROM clean_weekly_sales
GROUP BY calendar_year, demographic
ORDER BY calendar_year, demographic;


-- ============================================================================
-- Highest Performing Retail Customer Segments
-- Purpose:
-- Identifies the Age Band and Demographic combinations contributing
-- the highest Retail sales.
-- ============================================================================
SELECT
    age_band,
    demographic,
    SUM(sales)                                             AS retail_sales,
    ROUND(100.0 * SUM(sales) / SUM(SUM(sales)) OVER (), 2) AS pct_of_retail_sales
FROM clean_weekly_sales
WHERE platform = 'Retail'
GROUP BY age_band, demographic
ORDER BY retail_sales DESC;


-- ============================================================================
-- Average Transaction Calculation Validation
-- Purpose:
-- Demonstrates why averaging precomputed transaction values can produce
-- misleading results and shows the correct aggregation method.
-- ============================================================================


-- The avg_transaction column stores a per-row average (sales / transactions
-- for that individual row). Averaging it would produce a mean of means, which
-- gives incorrect results when group sizes differ. The correct approach is to
-- re-aggregate from the raw totals:

SELECT
    calendar_year,
    platform,
    -- WRONG approach (for illustration only — do not use for reporting):
    ROUND(AVG(avg_transaction), 2)            AS incorrect_avg_of_avgs,
    -- CORRECT approach: sum both numerator and denominator first:
    ROUND(SUM(sales) / SUM(transactions), 2)  AS correct_avg_transaction
FROM clean_weekly_sales
GROUP BY calendar_year, platform
ORDER BY calendar_year, platform;


-- ============================================================================
-- 4-Week Sales Comparison Around Packaging Change
-- Purpose:
-- Compares total sales for the four weeks before and after the sustainable
-- packaging implementation in Week 25 of 2020.
-- ============================================================================

-- We anchor on the week_number of the change date to make this robust
-- regardless of the date stored in the table.
WITH change_week AS (
    SELECT DISTINCT week_number AS change_week_num
    FROM clean_weekly_sales
    WHERE week_date = '2020-06-15'
),
period_totals AS (
    SELECT
        CASE
            WHEN cws.week_number BETWEEN cw.change_week_num - 4
                                     AND cw.change_week_num - 1 THEN 'before'
            WHEN cws.week_number BETWEEN cw.change_week_num
                                     AND cw.change_week_num + 3 THEN 'after'
        END                   AS period,
        SUM(cws.sales)        AS total_sales
    FROM clean_weekly_sales AS cws
    CROSS JOIN change_week AS cw
    WHERE cws.calendar_year = 2020
      AND cws.week_number BETWEEN cw.change_week_num - 4
                              AND cw.change_week_num + 3
    GROUP BY period
    HAVING period IS NOT NULL
)
SELECT
    period,
    total_sales,
    total_sales
        - LAG(total_sales) OVER (ORDER BY period DESC)             AS sales_change,
    ROUND(
        100.0 * (total_sales - LAG(total_sales) OVER (ORDER BY period DESC))
        / LAG(total_sales) OVER (ORDER BY period DESC),
        2
    )                                                              AS pct_change
FROM period_totals
ORDER BY period DESC;


-- ============================================================================
-- 12-Week Sales Comparison Around Packaging Change
-- Purpose:
-- Evaluates the long-term sales impact by comparing the twelve weeks
-- before and after the packaging change.
-- ============================================================================
WITH change_week AS (
    SELECT DISTINCT week_number AS change_week_num
    FROM clean_weekly_sales
    WHERE week_date = '2020-06-15'
),
period_totals AS (
    SELECT
        CASE
            WHEN cws.week_number BETWEEN cw.change_week_num - 12
                                     AND cw.change_week_num - 1  THEN 'before'
            WHEN cws.week_number BETWEEN cw.change_week_num
                                     AND cw.change_week_num + 11 THEN 'after'
        END                   AS period,
        SUM(cws.sales)        AS total_sales
    FROM clean_weekly_sales AS cws
    CROSS JOIN change_week AS cw
    WHERE cws.calendar_year = 2020
      AND cws.week_number BETWEEN cw.change_week_num - 12
                              AND cw.change_week_num + 11
    GROUP BY period
    HAVING period IS NOT NULL
)
SELECT
    period,
    total_sales,
    total_sales
        - LAG(total_sales) OVER (ORDER BY period DESC)             AS sales_change,
    ROUND(
        100.0 * (total_sales - LAG(total_sales) OVER (ORDER BY period DESC))
        / LAG(total_sales) OVER (ORDER BY period DESC),
        2
    )                                                              AS pct_change
FROM period_totals
ORDER BY period DESC;


-- ============================================================================
-- Multi-Year Packaging Change Comparison
-- Purpose:
-- Compares the 4-week and 12-week sales windows across all available years
-- to determine whether observed changes are seasonal or event-driven.
-- ============================================================================

-- 4-week window across all years:
WITH change_week AS (
    SELECT DISTINCT week_number AS change_week_num
    FROM clean_weekly_sales
    WHERE week_date = '2020-06-15'
),
period_totals AS (
    SELECT
        cws.calendar_year,
        CASE
            WHEN cws.week_number BETWEEN cw.change_week_num - 4
                                     AND cw.change_week_num - 1 THEN 'before'
            WHEN cws.week_number BETWEEN cw.change_week_num
                                     AND cw.change_week_num + 3 THEN 'after'
        END                   AS period,
        SUM(cws.sales)        AS total_sales
    FROM clean_weekly_sales AS cws
    CROSS JOIN change_week AS cw
    WHERE cws.week_number BETWEEN cw.change_week_num - 4
                              AND cw.change_week_num + 3
    GROUP BY cws.calendar_year, period
    HAVING period IS NOT NULL
)
SELECT
    calendar_year,
    period,
    total_sales,
    total_sales
        - LAG(total_sales) OVER (PARTITION BY calendar_year ORDER BY period DESC) AS sales_change,
    ROUND(
        100.0 * (total_sales - LAG(total_sales) OVER (PARTITION BY calendar_year ORDER BY period DESC))
        / LAG(total_sales) OVER (PARTITION BY calendar_year ORDER BY period DESC),
        2
    )                                                                              AS pct_change
FROM period_totals
ORDER BY calendar_year, period DESC;

-- 12-week window across all years:
WITH change_week AS (
    SELECT DISTINCT week_number AS change_week_num
    FROM clean_weekly_sales
    WHERE week_date = '2020-06-15'
),
period_totals AS (
    SELECT
        cws.calendar_year,
        CASE
            WHEN cws.week_number BETWEEN cw.change_week_num - 12
                                     AND cw.change_week_num - 1  THEN 'before'
            WHEN cws.week_number BETWEEN cw.change_week_num
                                     AND cw.change_week_num + 11 THEN 'after'
        END                   AS period,
        SUM(cws.sales)        AS total_sales
    FROM clean_weekly_sales AS cws
    CROSS JOIN change_week AS cw
    WHERE cws.week_number BETWEEN cw.change_week_num - 12
                              AND cw.change_week_num + 11
    GROUP BY cws.calendar_year, period
    HAVING period IS NOT NULL
)
SELECT
    calendar_year,
    period,
    total_sales,
    total_sales
        - LAG(total_sales) OVER (PARTITION BY calendar_year ORDER BY period DESC) AS sales_change,
    ROUND(
        100.0 * (total_sales - LAG(total_sales) OVER (PARTITION BY calendar_year ORDER BY period DESC))
        / LAG(total_sales) OVER (PARTITION BY calendar_year ORDER BY period DESC),
        2
    )                                                                              AS pct_change
FROM period_totals
ORDER BY calendar_year, period DESC;


-- ============================================================================
-- Regional Sales Impact Analysis
-- Purpose:
-- Measures the percentage change in regional sales before and after
-- the packaging implementation.
-- ============================================================================

WITH change_week AS (
    SELECT DISTINCT week_number AS change_week_num
    FROM clean_weekly_sales
    WHERE week_date = '2020-06-15'
),
period_sales AS (
    SELECT
        region,
        CASE
            WHEN cws.week_number BETWEEN cw.change_week_num - 12
                                     AND cw.change_week_num - 1  THEN 'before'
            WHEN cws.week_number BETWEEN cw.change_week_num
                                     AND cw.change_week_num + 11 THEN 'after'
        END        AS period,
        SUM(sales) AS total_sales
    FROM clean_weekly_sales AS cws
    CROSS JOIN change_week AS cw
    WHERE cws.calendar_year = 2020
      AND cws.week_number BETWEEN cw.change_week_num - 12
                              AND cw.change_week_num + 11
    GROUP BY region, period
    HAVING period IS NOT NULL
)
SELECT
    region,
    MAX(CASE WHEN period = 'before' THEN total_sales END) AS before_sales,
    MAX(CASE WHEN period = 'after'  THEN total_sales END) AS after_sales,
    MAX(CASE WHEN period = 'after'  THEN total_sales END)
        - MAX(CASE WHEN period = 'before' THEN total_sales END) AS sales_change,
    ROUND(
        100.0 * (
            MAX(CASE WHEN period = 'after'  THEN total_sales END)
            - MAX(CASE WHEN period = 'before' THEN total_sales END)
        ) / MAX(CASE WHEN period = 'before' THEN total_sales END),
        2
    ) AS pct_change
FROM period_sales
GROUP BY region
ORDER BY pct_change ASC;


-- ============================================================================
-- Platform Sales Impact Analysis
-- Purpose:
-- Evaluates how Retail and Shopify sales changed after the packaging update.
-- ============================================================================
WITH change_week AS (
    SELECT DISTINCT week_number AS change_week_num
    FROM clean_weekly_sales
    WHERE week_date = '2020-06-15'
),
period_sales AS (
    SELECT
        platform,
        CASE
            WHEN cws.week_number BETWEEN cw.change_week_num - 12
                                     AND cw.change_week_num - 1  THEN 'before'
            WHEN cws.week_number BETWEEN cw.change_week_num
                                     AND cw.change_week_num + 11 THEN 'after'
        END        AS period,
        SUM(sales) AS total_sales
    FROM clean_weekly_sales AS cws
    CROSS JOIN change_week AS cw
    WHERE cws.calendar_year = 2020
      AND cws.week_number BETWEEN cw.change_week_num - 12
                              AND cw.change_week_num + 11
    GROUP BY platform, period
    HAVING period IS NOT NULL
)
SELECT
    platform,
    MAX(CASE WHEN period = 'before' THEN total_sales END) AS before_sales,
    MAX(CASE WHEN period = 'after'  THEN total_sales END) AS after_sales,
    MAX(CASE WHEN period = 'after'  THEN total_sales END)
        - MAX(CASE WHEN period = 'before' THEN total_sales END) AS sales_change,
    ROUND(
        100.0 * (
            MAX(CASE WHEN period = 'after'  THEN total_sales END)
            - MAX(CASE WHEN period = 'before' THEN total_sales END)
        ) / MAX(CASE WHEN period = 'before' THEN total_sales END),
        2
    ) AS pct_change
FROM period_sales
GROUP BY platform
ORDER BY pct_change ASC;

-- ============================================================================
-- Age Band Sales Impact Analysis
-- Purpose:
-- Compares customer age groups to identify which experienced the largest
-- positive or negative sales change.
-- ============================================================================
WITH change_week AS (
    SELECT DISTINCT week_number AS change_week_num
    FROM clean_weekly_sales
    WHERE week_date = '2020-06-15'
),
period_sales AS (
    SELECT
        age_band,
        CASE
            WHEN cws.week_number BETWEEN cw.change_week_num - 12
                                     AND cw.change_week_num - 1  THEN 'before'
            WHEN cws.week_number BETWEEN cw.change_week_num
                                     AND cw.change_week_num + 11 THEN 'after'
        END        AS period,
        SUM(sales) AS total_sales
    FROM clean_weekly_sales AS cws
    CROSS JOIN change_week AS cw
    WHERE cws.calendar_year = 2020
      AND cws.week_number BETWEEN cw.change_week_num - 12
                              AND cw.change_week_num + 11
    GROUP BY age_band, period
    HAVING period IS NOT NULL
)
SELECT
    age_band,
    MAX(CASE WHEN period = 'before' THEN total_sales END) AS before_sales,
    MAX(CASE WHEN period = 'after'  THEN total_sales END) AS after_sales,
    MAX(CASE WHEN period = 'after'  THEN total_sales END)
        - MAX(CASE WHEN period = 'before' THEN total_sales END) AS sales_change,
    ROUND(
        100.0 * (
            MAX(CASE WHEN period = 'after'  THEN total_sales END)
            - MAX(CASE WHEN period = 'before' THEN total_sales END)
        ) / MAX(CASE WHEN period = 'before' THEN total_sales END),
        2
    ) AS pct_change
FROM period_sales
GROUP BY age_band
ORDER BY pct_change ASC;


-- ============================================================================
-- Demographic Sales Impact Analysis
-- Purpose:
-- Evaluates the impact of the packaging change across Couples and Families.
-- ============================================================================
WITH change_week AS (
    SELECT DISTINCT week_number AS change_week_num
    FROM clean_weekly_sales
    WHERE week_date = '2020-06-15'
),
period_sales AS (
    SELECT
        demographic,
        CASE
            WHEN cws.week_number BETWEEN cw.change_week_num - 12
                                     AND cw.change_week_num - 1  THEN 'before'
            WHEN cws.week_number BETWEEN cw.change_week_num
                                     AND cw.change_week_num + 11 THEN 'after'
        END        AS period,
        SUM(sales) AS total_sales
    FROM clean_weekly_sales AS cws
    CROSS JOIN change_week AS cw
    WHERE cws.calendar_year = 2020
      AND cws.week_number BETWEEN cw.change_week_num - 12
                              AND cw.change_week_num + 11
    GROUP BY demographic, period
    HAVING period IS NOT NULL
)
SELECT
    demographic,
    MAX(CASE WHEN period = 'before' THEN total_sales END) AS before_sales,
    MAX(CASE WHEN period = 'after'  THEN total_sales END) AS after_sales,
    MAX(CASE WHEN period = 'after'  THEN total_sales END)
        - MAX(CASE WHEN period = 'before' THEN total_sales END) AS sales_change,
    ROUND(
        100.0 * (
            MAX(CASE WHEN period = 'after'  THEN total_sales END)
            - MAX(CASE WHEN period = 'before' THEN total_sales END)
        ) / MAX(CASE WHEN period = 'before' THEN total_sales END),
        2
    ) AS pct_change
FROM period_sales
GROUP BY demographic
ORDER BY pct_change ASC;


-- ============================================================================
-- Customer Type Sales Impact Analysis
-- Purpose:
-- Compares before-and-after sales performance for each customer type
-- to identify the most affected customer groups.
-- ============================================================================
WITH change_week AS (
    SELECT DISTINCT week_number AS change_week_num
    FROM clean_weekly_sales
    WHERE week_date = '2020-06-15'
),
period_sales AS (
    SELECT
        customer_type,
        CASE
            WHEN cws.week_number BETWEEN cw.change_week_num - 12
                                     AND cw.change_week_num - 1  THEN 'before'
            WHEN cws.week_number BETWEEN cw.change_week_num
                                     AND cw.change_week_num + 11 THEN 'after'
        END        AS period,
        SUM(sales) AS total_sales
    FROM clean_weekly_sales AS cws
    CROSS JOIN change_week AS cw
    WHERE cws.calendar_year = 2020
      AND cws.week_number BETWEEN cw.change_week_num - 12
                              AND cw.change_week_num + 11
    GROUP BY customer_type, period
    HAVING period IS NOT NULL
)
SELECT
    customer_type,
    MAX(CASE WHEN period = 'before' THEN total_sales END) AS before_sales,
    MAX(CASE WHEN period = 'after'  THEN total_sales END) AS after_sales,
    MAX(CASE WHEN period = 'after'  THEN total_sales END)
        - MAX(CASE WHEN period = 'before' THEN total_sales END) AS sales_change,
    ROUND(
        100.0 * (
            MAX(CASE WHEN period = 'after'  THEN total_sales END)
            - MAX(CASE WHEN period = 'before' THEN total_sales END)
        ) / MAX(CASE WHEN period = 'before' THEN total_sales END),
        2
    ) AS pct_change
FROM period_sales
GROUP BY customer_type
ORDER BY pct_change ASC;
